import React, {useEffect, useRef, useState } from "react";
import Head from 'next/head'
import styles from '@/styles/about.module.scss'
import ScrollHandler from '../components/ScrollHandler/ScrollHandler'
import InfoCard from '../components/infoCards/infoCard'

const About = () => {
    const ref = useRef<HTMLDivElement>(null);

    const [contentHeight, setContentHeight] = useState<number | undefined>(0);
    const [isHealthExpanded, setHealthExpanded] = useState(false);

    const contentRef = useRef<HTMLDivElement>(null);

    useEffect(() => {
        if (isHealthExpanded) {
            setContentHeight(contentRef.current?.scrollHeight);
        } else {
            setContentHeight(0);
        }
    }, [isHealthExpanded]);

    const expandHealth = () => {
        setHealthExpanded(!isHealthExpanded)
    }

return(
    <div className={styles.body} id='/about'>
        <Head>
            <title>Job Derksen</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />

            <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className={styles.gradient}>
            <section className={styles.hero}>
                <h1 ref={ref} className={styles.pageTitle}>ABOUT ME</h1>
            </section>
        </div>
        <div className={styles.container}>
            <h3 className='mainText'>
                Hi, I'm Job. A final year student studying my masters in computing and electronic systems.
                Currently working as a bartender, but looking for a career change once I graduate.
            </h3>
            <h4>
                Born the 19<sup>th</sup> of April 2001 in Leidschendam Netherlands (near The Hague).
            </h4>
            <h5 className='sectionHead' onClick={expandHealth}>Education</h5>
            <div className={styles.balls} style={{height: contentHeight, overflow: 'hidden', transition: 'height 0.4s ease'}}>
                <div ref={contentRef} className={styles.rowContainer}>
                    <InfoCard
                        image={'Image of my Uni'}
                        heading={'The University of Strathclyde'}
                        bodyText={'I went to Uni here'}
                    />
                    <InfoCard
                        image={'Image of AGS'}
                        heading={'Aberdeen Grammar School'}
                        bodyText={'I went to school here'}
                    />
                </div>
            </div>
            <h4></h4>
            <a>Skills</a>
        </div>
        <ScrollHandler className={styles.pageTitle_scroll} elementRef={ref} initialScrollMultiplier={0.5}
                       endScrollMultiplier={0.9}/>
    </div>
)
}
export default About;
