import React, {useEffect, useRef, useState } from "react";
import Head from 'next/head'
import styles from '@/styles/about.module.scss'
import ScrollHandler from '../components/ScrollHandler/ScrollHandler'
import InfoCard from '../components/infoCards/infoCard'
import Strathclyde from '../../public/university-of-strathclyde-banner.png'
import ags from '../../public/aberdeen grammar school.jpg'

const About = () => {
    const ref = useRef<HTMLDivElement>(null);
    const ref2 = useRef<HTMLDivElement>(null);

    const [contentHeight, setContentHeight] = useState<number | undefined>(0);
    const [isHealthExpanded, setHealthExpanded] = useState(false);

    const contentRef = useRef<HTMLDivElement>(null);

    useEffect(() => {
        if (isHealthExpanded) {
            setContentHeight(contentRef.current?.scrollHeight);
        } else {
            setContentHeight(0);
        }
    }, [isHealthExpanded]);

    const expandHealth = () => {
        setHealthExpanded(!isHealthExpanded)
    }

return(
    <div className={styles.body} id='/about'>
        <Head>
            <title>Job Derksen</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />

            <link rel="icon" href="/favicon.ico" />
        </Head>
        <div ref={ref2} className={styles.gradient}>
            <section className={styles.hero}>
                <h1 ref={ref} className={styles.pageTitle}>ABOUT ME</h1>
            </section>
        </div>
        <div className={styles.container}>
            <h3 className='mainText'>
                Hi, I am Job. A final year student studying my masters in computing and electronic systems.
                Currently working as a bartender, but looking for a career change once I graduate.
            </h3>
            <h4>
                Born the 19<sup>th</sup> of April 2001 in Leidschendam Netherlands (near The Hague).
            </h4>
            <h4 className='sectionHead' onClick={expandHealth}>Education</h4>
            <div className={styles.balls} style={{height: contentHeight, overflow: 'hidden', transition: 'height 0.4s ease'}}>
                <div ref={contentRef} className={styles.rowContainer}>
                    <InfoCard
                        img={Strathclyde}
                        description={'Strathclyde Image'}
                        heading={'The University of Strathclyde'}
                        bodyText={'2019 - 2024'}
                    />
                    <InfoCard
                        img={ags}
                        description={'Aberdeen Grammar School Image'}
                        heading={'Aberdeen Grammar School'}
                        bodyText={'2013 - 2019'}
                    />
                </div>
            </div>
            <h4></h4>
            <h4 className='sectionHead'>Skills</h4>
        </div>

        <ScrollHandler
            className={styles.pageTitle_scroll}
            elementRef={ref}
            initialScrollMultiplier={0.5}
            endScrollMultiplier={0.9}
        />

        <ScrollHandler
            className={styles.gradient_after}
            elementRef={ref2}
            initialScrollMultiplier={0.8}
            endScrollMultiplier={3}
        />
    </div>
)
}
export default About;
