import React from "react";
import Head from "next/head";
import {Navigation} from "@/components/navigation/Navigation";
const Contact = () => {
    return(
        <div className='pageContainer' id='/contact'>
            <Head>
                <title>Contact Me</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
                <div className='content'>
                    Contact me
                </div>
        </div>
    )
}
export default Contact;