import React, {useEffect, useState } from "react";
import Head from "next/head";
import styles from '@/styles/Contact.module.scss'
import clsx from 'clsx';

const Contact: React.FC = () => {
    const [badgeLoaded, setBadgeLoaded] = useState<boolean>(false);

    useEffect(() => {
        const script = document.createElement('script');
        script.src = 'https://platform.linkedin.com/badges/js/profile.js';
        script.async = true;
        script.defer = true;

        const handleLoad = () => {
            setBadgeLoaded(true);
        };

        const handleError = () => {
            setBadgeLoaded(false);
        };

        script.onload = handleLoad;
        script.onerror = handleError;

        document.head.appendChild(script);

        return () => {
            document.head.removeChild(script);
        };
    }, []);

    return (
        <div className='pageContainer' id='/contact'>
            <Head>
                <title>Job Derksen</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
                <script src="https://platform.linkedin.com/badges/js/profile.js" async defer></script>
            </Head>
            <div className='content'>
                <h2 className='pageTitle'>
                Contact Me
                </h2>

                <div className='linkedin'>
                    <div className={styles.linkedinBadgeContainer}>
                        <div className="badge-base LI-profile-badge"
                             data-locale="en_US"
                             data-size="medium"
                             data-theme="light"
                             data-type="HORIZONTAL"
                             data-vanity="jobderksen"
                             data-version="v1"
                        >
                            <div>
                            </div>
                            <p className={clsx({
                                [styles['yes']]: !badgeLoaded,
                                [styles['hidden']]: badgeLoaded
                            })}>
                                If the Linkedin Badge does not load use
                                <a href="https://uk.linkedin.com/in/jobderksen?trk=profile-badge">
                                    to visit my profile.
                                </a>.
                            </p>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    )
}
export default Contact;
