import React from "react";
import Head from "next/head";
import {PageComponent} from "@/components/pageComponent/PageComponent";
const Contact = () => {
    return(
        <>
            <Head>
                <title>Contact Me</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <PageComponent>
                <div className='content'>
                    Contact me
                </div>
            </PageComponent>
        </>
    )
}
export default Contact;