import Head from "next/head";
import React from "react";
const Home: React.FC = () => {
    return (
        <div className='pageContainerHome' id='/'>
            <Head>
                <title>Job Derksen</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div className='content'>
                <h1>Hi, my name is Job Derksen...</h1>
            </div>
        </div>
    );
}
export default Home;