import Head from "next/head";
import React from "react";
import styles from '@/styles/Home.module.scss'

const Home: React.FC = () => {
    return (
        <div className='pageContainerHome' id='/'>
            <Head>
                <title>Job Derksen</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div className={styles.container}>
                <h1 className={styles.title}>Job Derksen</h1>
                <h2 className={styles.subTitle}>Developer / Engineer / Bartender</h2>
                    {/* CREDIT - https://www.pexels.com/video/foggy-day-by-the-mountain-9130080/*/}
                <video src={require('../../public/video2.mp4')}
                       autoPlay
                       muted
                       loop
                       playsInline
                       className={styles.video}
                />
            </div>
        </div>
    );
}
export default Home;
