import Head from "next/head";
import React from "react";
const Home: React.FC = () => {
    return (
        <div className='pageContainerHome' id='/'>
            <Head>
                <title>Job Derksen</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div className='content'>
                <h1 style={{fontSize:100, fontWeight:900}}>
                    {/* eslint-disable-next-line react/no-unescaped-entities */}
                    Hi I'm Job <span style={{fontSize:10}}>(pronounced yob)</span>
                </h1>

            </div>
        </div>
    );
}
export default Home;