import Head from 'next/head'
import {PageComponent} from "@/components/pageComponent/PageComponent";
import Link from 'next/link'
export default function Home() {
  return (
    <>
      <Head>
        <title>Job Derksen</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageComponent>
        <div className='content'>
            Home Page
        </div>
      </PageComponent>
    </>
)
}
