import Head from 'next/head'
import {Navigation} from "@/components/navigation/Navigation";
import About from '@/pages/about'
import Contact from '@/pages/contact'
import Project from '@/pages/projects'
export default function Home() {

    const Home = () => {
        return (
            <div className='pageContainer' id='/'>
                <div className='content'>
                    Home Page
                </div>
            </div>
        );
    }

    return (
        <>
            <Head>
                <title>Job Derksen</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navigation/>
            <Home/>
            <About/>
            <Project/>
            <Contact/>

    </>
)
}
