import React, {useEffect, useRef, useState} from "react";
import Head from "next/head";
import styles from '@/styles/projects.module.scss'
import ScrollHandler from "@/components/ScrollHandler/ScrollHandler";
import ParticlesComp from "@/particles/Particles";
import clsx from "clsx";
import useWindowDimensions from "../hooks/useWindowDimensions"

const Projects = () => {
    const aboutRef = useRef<HTMLDivElement>(null);
    const gradientRef = useRef<HTMLDivElement>(null);

    const [contentHeightBanner, setContentHeightBanner] = useState<number>(0);
    const heroSizeRef = useRef<HTMLDivElement>(null);

    const [showParticles, setShowParticles] = useState(false)

    const screenWidth = useWindowDimensions().width;

    useEffect(() => {
        const observer = new ResizeObserver((entries) => {
            setContentHeightBanner(entries[0].contentRect.height);
        });
        if (heroSizeRef.current) {
            observer.observe(heroSizeRef.current);
        }
        return () => {
            if (heroSizeRef.current) {
                // eslint-disable-next-line react-hooks/exhaustive-deps
                observer.unobserve(heroSizeRef.current);
            }
        };
    }, []);

    useEffect(() => {
        if(screenWidth < 1024){
            if(contentHeightBanner > (92)){
                setShowParticles(true)
            } else{
                setShowParticles(false)
            }
        }else {
            if(contentHeightBanner > (184)){
                setShowParticles(true)
            } else{
                setShowParticles(false)
            }
        }
    }, [contentHeightBanner, screenWidth]);

    const balls = () => {
        if(screenWidth < 1024) return 2.55
        else return 2.35
    }

    return(
        <div className={styles.container} id='#portfolio'>
            <Head>
                <title>Job Derksen</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div style={{height: contentHeightBanner, overflow: 'hidden'}}>
                <div ref={gradientRef} className={styles.gradient}>
                    <section className={styles.hero} ref={heroSizeRef}>
                        <h1 ref={aboutRef} className={styles.pageTitle}>PORTFOLIO</h1>
                    </section>
                    <section className={clsx({
                        [styles['particleWidth']]: !showParticles,
                        [styles['particleWidth__after']]: showParticles,
                    })}>
                        <ParticlesComp init={showParticles}/>
                    </section>
                </div>
            </div>

            <div>
                My projects
                {/*https://www.energyvoice.com/oilandgas/north-sea/188096/aberdeen-school-scoops-top-oil-and-gas-challenge/*/}
                {/*https://www.agcc.co.uk/news-article/aberdeen-grammar-school-wins-top-prize-at-final-of-techfests-stem-in-the-pipeline-oil-and-gas-challenge*/}

            </div>
            <ScrollHandler
                className={styles.pageTitle_scroll}
                elementRef={aboutRef}
                initialScrollMultiplier={2}
                endScrollMultiplier={balls()}
            />

            <ScrollHandler
                className={styles.gradient_after}
                elementRef={gradientRef}
                initialScrollMultiplier={2}
                endScrollMultiplier={20}
            />
        </div>
    )
}
export default Projects;
