import React, {useEffect, useRef, useState} from "react";
import Head from "next/head";
import styles from '@/styles/projects.module.scss'
import ScrollHandler from "@/components/ScrollHandler/ScrollHandler";
import ParticlesComp from "@/particles/Particles";
import clsx from "clsx";
import useWindowDimensions from "../hooks/useWindowDimensions"
import GreenkeeperCarousel from "../components/carousel/greenkeeperCarousel";
import PortfolioCard from '../components/cards/portfolioCard'
import CheckoutCarousel from "@/components/carousel/checkoutCarousel";
import TachometerCarousel from "@/components/carousel/tachometerCarousel";
import Image from "next/image";
import EmptyCalc from "@/assets/projects/billSplitter/EmptyCalc.jpg";
import FilledCalc from "@/assets/projects/billSplitter/FilledCalc.jpg";
import SelectCurrency from "@/assets/projects/billSplitter/SelectCurrency.jpg";
import BostonMetroCarousel from "@/components/carousel/bostonMetroCarousel";
import Model from '@/components/3Dmodel/3DModel'

const Projects = () => {
    const portfolioRef = useRef<HTMLDivElement>(null);
    const gradientRef = useRef<HTMLDivElement>(null);

    const [contentHeightBanner, setContentHeightBanner] = useState<number>(0);
    const heroSizeRef = useRef<HTMLDivElement>(null);

    const [showParticles, setShowParticles] = useState(false)
    const [flip, setFlip] = useState(false)

    const screenWidth = useWindowDimensions().width;

    useEffect(() => {
        const observer = new ResizeObserver((entries) => {
            setContentHeightBanner(entries[0].contentRect.height);
        });
        if (heroSizeRef.current) {
            observer.observe(heroSizeRef.current);
        }
        return () => {
            if (heroSizeRef.current) {
                // eslint-disable-next-line react-hooks/exhaustive-deps
                observer.unobserve(heroSizeRef.current);
            }
        };
    }, []);

    useEffect(() => {
        if(screenWidth <= 1024){
            setFlip(true)
            if(contentHeightBanner > (92)){
                setShowParticles(true)
            } else{
                setShowParticles(false)
            }
        }else {
            setFlip(false)
            if(contentHeightBanner > (183)){
                setShowParticles(true)
            } else{
                setShowParticles(false)
            }
        }
    }, [contentHeightBanner, screenWidth]);

    return(
        <div className={styles.container} id='#portfolio'>
            <Head>
                <title>Job Derksen</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <header style={{height: contentHeightBanner, overflow: 'hidden'}}>
                <div ref={gradientRef} className={styles.gradient}>
                    <section className={styles.hero} ref={heroSizeRef}>
                        <h1 ref={portfolioRef} className={styles.pageTitle}>PORTFOLIO</h1>
                    </section>
                    <section className={clsx({
                        [styles['particleWidth']]: !showParticles,
                        [styles['particleWidth__after']]: showParticles,
                    })}>
                        <ParticlesComp init={showParticles}/>
                    </section>
                </div>
            </header>
            {/*https://www.energyvoice.com/oilandgas/north-sea/188096/aberdeen-school-scoops-top-oil-and-gas-challenge/*/}
            {/*https://www.agcc.co.uk/news-article/aberdeen-grammar-school-wins-top-prize-at-final-of-techfests-stem-in-the-pipeline-oil-and-gas-challenge*/}
            <main className={styles.main}>
                <h4 className='sectionHead' style={{color:'#e0e0e0e0'}}>University Projects <span
                    style={{fontStyle:'italic'}}>2019 - Present</span>
                </h4>
                <PortfolioCard
                    title={'Robotic Greenkeeper'}
                    skills={'Next.js, Typescript, SCSS, HTML, Python, Arduino(C++), Cloud Computing(AWS, Web hosting and APIs), Artificial Intelligence, Gira, Teamwork'}
                    type={'Group Meng Computing & Electronic Electrical Engineering Project '}
                    year={'2023 - Current'}
                    description={
                        'This group project is the culmination of my whole educational career and is thus far the highlight. ' +
                        'This project is a challenge and takes into the computing side and electronic engineering side ' +
                        'and is so far the most valuable experience I have had the pleasure to be a part of. This project ' +
                        'is creating a robot which is to scan a golf green to look for and fix pitch marks, indents caused ' +
                        'by the ball landing onto the surface. It also is to classify the health of the soil on the green ' +
                        'by testing the nutrient composition.'
                    }
                    url={"https://main.d1knm3fjtjv9v5.amplifyapp.com/"}
                    swap={true}
                    flip={flip}
                >
                    <GreenkeeperCarousel/>
                </PortfolioCard>
                <PortfolioCard
                    title={'Checkout Assistant'}
                    skills={'React Native, Javascript, SQL, PHP, APIs'}
                    type={'Fourth Year Project, Mobile App'}
                    year={'2022 - 2023'}
                    description={''}
                    url={""}
                    swap={false}
                    flip={flip}
                >

                    <CheckoutCarousel/>
                </PortfolioCard>
                <PortfolioCard
                    title={'Tachometer'}
                    skills={'React Native, Javascript, PCB design, Soldering'}
                    type={'Third Year Group Project, Mobile App'}
                    year={'2021 - 2022'}
                    description={''}
                    url={""}
                    swap={true}
                    flip={flip}
                >

                    <TachometerCarousel/>
                </PortfolioCard>
                <PortfolioCard
                    title={'Bill Splitter'}
                    skills={'Javascript, APIs, HTML, CSS, MVC'}
                    type={'Third Year Solo Project, Web/Mobile App'}
                    year={'2022'}
                    description={''}
                    url={""}
                    swap={false}
                    flip={flip}
                >

                    <div className={styles.imageContainer}>
                        <Image
                            src={SelectCurrency}
                            alt={'home page of app'}
                            priority={true}
                            className={styles.image}
                        />
                        <Image
                            src={EmptyCalc}
                            alt={'home page of app scrolled further'}
                            priority={true}
                            className={styles.image}
                        />
                        <Image
                            src={FilledCalc}
                            alt={'health of green'}
                            priority={true}
                            className={styles.image}
                        />

                    </div>
                </PortfolioCard>
                <PortfolioCard
                    title={'Boston Metro System'}
                    skills={'Java, Sorting Algorithms, OOP, Agile, Swing'}
                    type={'Third Year Project, Mobile App'}
                    year={'2022'}
                    description={''}
                    url={""}
                    swap={true}
                    flip={flip}
                >

                    <BostonMetroCarousel/>
                </PortfolioCard>
                <h4 className='sectionHead' style={{color: '#e0e0e0e0'}}>Personal Projects <span
                    style={{fontStyle: 'italic'}}>2021 - Present</span>
                </h4>
                <PortfolioCard
                    title={'Calorie Tracking Mobile App'}
                    skills={'React Native'}
                    type={'Group Meng Computing & Electronic Electrical Engineering Project '}
                    year={'2022'}
                    description={''}
                    url={""}
                    swap={false}
                    flip={flip}
                >
                    <GreenkeeperCarousel/>
                </PortfolioCard>
                <PortfolioCard
                    title={'This Website'}
                    skills={'React Native, '}
                    type={'Fourth Year Project, Mobile App'}
                    year={'Current'}
                    description={''}
                    url={""}
                    swap={true}
                    flip={flip}
                >

                    <CheckoutCarousel/>
                </PortfolioCard>
                <h4 className='sectionHead' style={{color: '#e0e0e0e0'}}>School Projects <span
                    style={{fontStyle: 'italic'}}>2017 - 2019</span>
                </h4>
                <PortfolioCard
                    title={'F1 in Schools'}
                    skills={''}
                    type={'Extra Curricular Project'}
                    year={'2018-2019'}
                    description={''}
                    url={""}
                    swap={false}
                    flip={flip}
                >
                    <div className={styles.image}>
                        <Model/>
                    </div>
                </PortfolioCard>
                <PortfolioCard
                    title={'Stem in the Pipeline'}
                    skills={''}
                    type={'Extra Curricular Project'}
                    year={'2019'}
                    description={''}
                    url={""}
                    swap={true}
                    flip={flip}
                >

                    <CheckoutCarousel/>
                </PortfolioCard>
            </main>
            <ScrollHandler
                className={styles.pageTitle_scroll}
                elementRef={portfolioRef}
                startScrollOffset={-100}
                scrollMultiplier={3.5}
                endScrollOffset={368}
            />

            <ScrollHandler
                className={styles.gradient_after}
                elementRef={gradientRef}
                startScrollOffset={-100}
                scrollMultiplier={3.5}
                endScrollOffset={368}
            />
        </div>
    )
}
export default Projects;
